[files]
extend-exclude = [
    "Cargo.lock",
    "docs/*.pdf",
]

[default]
extend-ignore-re = [
    "seccomp-bpf",
]

[default.extend-words]
CapInh = "CapInh"
crate = "crate"
EOF = "EOF"
inh = "inh"
