[graph]
all-features = true

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"

[licenses]
version = 2
confidence-threshold = 0.92
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-3.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
]
